// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dttxomlxzmvrslmxekio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dHhvbWx4em12cnNsbXhla2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Njg5NzAsImV4cCI6MjA2NDI0NDk3MH0.mlpleCyOn-l8jegz7J9ud1szKrMuUVKkrIAbIpFEH3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);